#version 450
#extension GL_ARB_shading_language_include : enable
#extension GL_ARB_shader_draw_parameters : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_samplerless_texture_functions : require
#extension GL_EXT_shader_image_load_formatted : require
#extension GL_EXT_scalar_block_layout : enable

#include "CommonData.glsl"

layout(local_size_x = 256) in;

layout(set = 0, binding = 0) readonly uniform U_Camera
{
	mat4 view;
	mat4 projection;
    mat4 viewInverse;
    mat4 projInverse;
    
    mat4 prevView;
	mat4 prevProjection;
	mat4 prevViewInverse;
	mat4 prevProjInverse;
}u_Camera;

// BATCH_ALL
layout(set = 1, binding = 0) readonly buffer SSBO_Model
{
	Transform transform[];
}ssbo_Model;

layout(set = 1, binding = 1) buffer SSBO_DrawIndexedCommands {
    IndircetDrawIndexedCommand drawIndexedCommands[];
}ssbo_DrawIndexedCommands;

layout(set = 1, binding = 2) buffer readonly SSBO_BoundingBoxBuffer {
    AABB boundingBoxList[];
};

layout(set = 2, binding = 0) uniform FrustumPlanes {
    vec4 planes[6];
};

bool IsAABBInFrustum(AABB aabb, uint index) 
{
    vec4 newMinPos = ssbo_Model.transform[index].currentModel * aabb.minPos;
    vec4 newMaxPos = ssbo_Model.transform[index].currentModel * aabb.maxPos;
    
    for (int i = 0; i < 6; ++i) 
    {
        vec3 positiveVertex = newMinPos.xyz;

        if (planes[i].x >= 0) positiveVertex.x = newMaxPos.x;
        if (planes[i].y >= 0) positiveVertex.y = newMaxPos.y;
        if (planes[i].z >= 0) positiveVertex.z = newMaxPos.z;

        float distance = dot(planes[i].xyz, positiveVertex) + planes[i].w;

        if (distance < 0) 
        {
            return false;
        }
    }

    return true;
}

void main() {
    uint idx = gl_GlobalInvocationID.x;
    
    if (IsAABBInFrustum(boundingBoxList[idx], idx)) 
    {
        ssbo_DrawIndexedCommands.drawIndexedCommands[idx].instanceCount = 1;
    }
    else 
    {
        ssbo_DrawIndexedCommands.drawIndexedCommands[idx].instanceCount = 0;
    }
}
